sudo: required
services:
    - docker
language: minimal

after_success:
    # - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    # - docker login -u$DOCKER_USER -p$DOCKER_PASS
    - docker login -e="$DOCKER_MAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
    - ./autobuild "latest"
    - ./autobuild "$(git describe --tags $(git rev-list --tags --max-count=1))"
    - docker logout
